# numpy란?
* Numerical Python 과학적, 산업적 연산을 위한 파이썬 패키지
* 다차원 배열, 행렬 연산에 주로 사용

In [1]:
# !pip install numpy
# !conda install numpy

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# 차원

* 0차원 = 점 . 스칼라

* 1차원 = 선 ---------------------- 벡터 [1,2,3,4,5] <br>
[1]<br>
[2]<br>
[3]<br>
[4]<br>
[5]<br>
* 벡터는 방향을 가진 데이터

* 2차원 = 면 ㅁ

* 3차원 공간, 입체

* 4차원 = ?3차원 요소가 2개 이상

In [7]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])

In [14]:
# 몇 차원?
a.ndim

1

In [29]:
c = np.array([[[1,2,3,4,5],[1,2,3,4,5]]])
c

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [22]:
d = np.array([[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]])
d

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [23]:
c.ndim

3

In [24]:
e = np.array([[[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]])
e

array([[[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]]])

In [25]:
e.ndim

4

In [27]:
f = np.array([[[[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]], [[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]]])
f

array([[[[[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]]],


        [[[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 5]]]]])

In [30]:
c.shape

(1, 2, 5)

# numpy를 사용하는 이유 : 행렬 연산이 쉽고 빠르기 때문에

In [31]:
a = 10

In [32]:
scalar = a+1

In [33]:
scalar

11

* 벡터연산

In [34]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [36]:
c = [5,6,7,8,9]

In [37]:
hap = []

for num in c:
    hap.append(num + 3)
hap
    

[8, 9, 10, 11, 12]

In [39]:
# 반복문을 사용하지 않아도됨
b + 3

array([4, 5, 6, 7, 8])

In [40]:
b * 8

array([ 8, 16, 24, 32, 40])

* 2차원 연산

In [41]:
d = [[1,2,3],[1,2,3],[1,2,3]]
d

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

* 2차원 연산  + 5하기

In [42]:
for i in d:
    print(i)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [45]:
hap = []
for i in d:
    temp = []
    for j in i:
        temp.append(j+5)
    hap.append(temp)
hap

[[6, 7, 8], [6, 7, 8], [6, 7, 8]]

In [47]:
d2 = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [48]:
d2 + 5

array([[6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

# numpy에서 자주 사용하는 메서드
* .ndim : 몇차원인지 보는 거
* .shape : 몇 차원, 몇 행 몇 열로 되어있는지 구조 확인
* .size : 배열 안에 있는 요소의 총 갯수가 몇 개인지
* .dtype : 데이터 타입이 무엇인지
* .itemsize : 1개 자료의 크기는 몇 인지

In [49]:
d2.ndim

2

In [50]:
d2.shape

(3, 3)

In [51]:
d2.size

9

In [52]:
d3 = d2/2
d3

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [53]:
d3.dtype

dtype('float64')

# ndarray 만들기
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다

In [55]:
np.array((1,2,3,4,5)) # 이렇게 하던가 ([1,2,3,4,5]) 리스트나 튜플로 만들어야됨

array([1, 2, 3, 4, 5])

In [56]:
np.array([1,2,3,4,5.3])

array([1. , 2. , 3. , 4. , 5.3])

In [57]:
e = np.array([1,2,3,4,5])
e.dtype

dtype('int64')

In [59]:
# 하나만 실수인  5.3이지만 하나로 인해서 실수로 type이 지정됨
e2 = np.array([1,2,3,4,5.3])
print(e2.dtype)
print(e2)

float64
[1.  2.  3.  4.  5.3]


In [61]:
# 문자열로 바뀜
e3 = np.array([1,2,'3',4,5.3])
print(e3.dtype)
print(type(e3))
print(e3)

<U32
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5.3']


In [63]:
for i in e3:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [64]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
np.arange(3,101,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

* reshape(행, 열)  벡터를 원하는 크기의 matrix또는 다차원 배열로 변환 

In [67]:
a = np.arange(24)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [68]:
[0,1,2],[3,4,5]

([0, 1, 2], [3, 4, 5])

In [70]:
# (2차 2행이 2개 있고) 그게 3개 있다고?
c = a.reshape(3,2,2,2)
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [71]:
d = c.reshape(24,)
print(d)
print(d.ndim)
print(d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


* flatten() 다차원 데이터를 1차원 배열로 바꿔주는 함수

In [72]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

* np.flip(데이터) 행렬의 순서를 뒤집을 때

In [73]:
np.flip(c)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [74]:
c[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
* np.linspace(시작, 끝, 구간 수)

In [83]:
f = np.array([5,7,11,1,3,2,54,0.5,0.6])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0.5,  0.6])

In [82]:
# 저장이 됨
f.sort()

In [84]:
# 이건 저장이 안됨
sorted(f, reverse = True)

[np.float64(54.0),
 np.float64(11.0),
 np.float64(7.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(0.5)]

# argsort() 자료중 값이 작은 것에서 큰 순으로 인덱스 출력

In [85]:
g = np.array([5,0.5, -7, 42, 10])
g

array([ 5. ,  0.5, -7. , 42. , 10. ])

In [86]:
g.argsort()

array([2, 1, 0, 4, 3])

In [87]:
sorted(g.argsort())

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [88]:
g2 = g[sorted(g.argsort())]
g2

array([ 5. ,  0.5, -7. , 42. , 10. ])

# 배열 합치기
np.concatenate()

In [92]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


* np.concatenate((a,b)) 의 기본 병합 방향은 행방향(가로), axis = 0 / 열방향(세로)으로 주고 싶으면  axis = 1
* 행방향으로 합칠 때는 두 행렬의 열의 길이가 같아야 합쳐짐

In [94]:
concat_row = np.concatenate((a,b))
print(concat_row.shape)
concat_row

(4, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

* axis = 1은 열방향으로 붙음
* 두 행렬의 행 길이가 같아야 붙음

In [96]:
concat_col = np.concatenate((a,b), axis = 1)
print(concat_col.shape)
print(concat_col)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


# 합치는 방향의 모양이 일치하지 않으면 합치지 X

In [100]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6]])
print(c)
print(c.shape)
print(c.ndim)
print(d)
print(d.shape)
print(d.ndim)

[[1 2]
 [3 4]]
(2, 2)
2
[[5 6]]
(1, 2)
2


In [98]:
concat_row2 = np.concatenate((c,d), axis = 0)
print(concat_row2.shape)
print(concat_row2)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [110]:
concat_col2 = np.concatenate((c,d.T), axis = 1)
print(concat_col2.shape)
print(concat_col2)

(2, 3)
[[1 2 5]
 [3 4 6]]


## 벡터와 매트릭스는 합칠 수 없다.

In [103]:
e = np.array([[1,2],[3,4]])
f = np.array([[5,6]])
print(e)
print(e.shape)
print(e.ndim)
print(f)
print(f.shape)
print(f.ndim)

[[1 2]
 [3 4]]
(2, 2)
2
[[5 6]]
(1, 2)
2


In [106]:
concat_row3 = np.concatenate((e,f), axis = 0)
print(concat_row3.shape)
print(concat_row3)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [107]:
concat_col3 = np.concatenate((e,f), axis = 1)
print(concat_col3.shape)
print(concat_col3)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [112]:
g = np.array([[1,2],[3,4]])
h = np.array([[5,6,7]])
print(g)
print(g.shape)
print(g.ndim)
print(h)
print(h.shape)
print(h.ndim)

[[1 2]
 [3 4]]
(2, 2)
2
[[5 6 7]]
(1, 3)
2


In [113]:
concat_row4 = np.concatenate((e,f), axis = 0)
print(concat_row4.shape)
print(concat_row4)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [115]:
concat_col4 = np.concatenate((e,f.T), axis = 1)
print(concat_col4.shape)
print(concat_col4)

(2, 3)
[[1 2 5]
 [3 4 6]]


# 전치 행렬 만들기
* .T
* .transpose()
* .reshape()

In [117]:
print(h)
print(h.shape)

[[5 6 7]]
(1, 3)


In [118]:
h2 = h.T
print(h2)
print(h2.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [123]:
h3 = h.transpose()
print(h3)
print(h3.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [121]:
h3.reshape(3,1)

array([[5],
       [6],
       [7]])

In [124]:
h4 = h.reshape(3,1)
print(h4)
print(h4.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [126]:
i = np.arange(6).reshape(3,2) # 3행 2열로 만들기
print(i)
print(i.shape)
print(i.ndim)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2


In [127]:
i2 = i.T
print(i2)
print(i2.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [129]:
i3 = i.transpose()
print(i3)
print(i3.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [130]:
i4 = i.reshape(2,3)
print(i4)
print(i4.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


## 브로드 캐스팅
* 벡터와 스칼라, 또는 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰 주는 것

In [134]:
a = np.arange(1,16).reshape(3,5)
print(a.shape)
print(a)

(3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [132]:
a + 3

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [136]:
b = np.array([1,2,3,4,5])
print(a.shape)
print(b.shape)
c = a+b

(3, 5)
(5,)


In [137]:
c[2][:3][::-1]

array([16, 14, 12])